# config/config.yaml
# ------------------------------------------------------
# Configuration file for PureMilk Snakemake Pipeline
#
# Defines all paths, thresholds, script locations.
# 
# Only this file needs to be edited to adjust thresholds, protein selection,
# or update paths without modifying the Snakefile.
# ------------------------------------------------------

# config/config.yaml
# ------------------------------------------------------
# Configuration file for PureMilk Snakemake Pipeline
# ------------------------------------------------------

# Login information for BacDive and NCBI
login:
  bacdive_info: "config/login/bacdive_info.txt"
  ncbi_info: "config/login/ncbi_info.txt"

# BepiPred 3.0 configuration
bepipred:
  # Path to BepiPred 3.0 installation (clone from https://github.com/UberClifford/BepiPred3.0-Predictor)
  path: "tools/BepiPred3.0"
  # Prediction method: 'vt_pred' (recommended) or 'mjv_pred'
  method: "vt_pred"
  # Epitope score threshold (0.0-1.0, higher = more confident predictions)
  threshold: 0.5
  # Minimum epitope length (amino acids)
  min_epitope_length: 6
  # Top percentage of epitope residues to include (0.0-1.0, 0.2=20%, 0.5=50%)
  top_percentage: 0.5

# BacDive data files
bacdive:
  species: "config/species/cow_milk/unique_species.txt"
  all_json: "data/bacdive/all_species.json"
  not_found: "data/bacdive/not_found.txt"
  updated_not_found: "data/bacdive/updated_not_found.txt"
  errors: "data/bacdive/errors.txt"
  downloaded: "data/bacdive/downloaded.txt"
  gram_classification: "data/bacdive/gram_classification.tsv"
  updated_gram_classification: "data/bacdive/updated_gram_classification.tsv"
  gram_positive: "data/bacdive/gram_positive.txt"
  gram_negative: "data/bacdive/gram_negative.txt"
  gram_species_template: "data/bacdive/{analysis}/gram_{group}.txt"

# QuickGO files
quickgo:
  go_ids: "config/quickgo/go_ids.tsv"
  taxon_ids: "config/quickgo/taxon_ids.tsv"
  annotations: "data/quickgo/annotations_all.json"
  genes: "data/quickgo/gene_symbols.txt"
  filtered_genes: "data/quickgo/params_1/gene_symbols_filtered.txt"
  surface_accessible: "config/quickgo/surface_accessible.txt"

# Paths for gene coverage analysis
gene_coverage:
  coverage_template: "results/gene_coverage_gram_{group}.tsv"
  checked_genes_template: "results/list_gene_coverage_gram_{group}.txt"
  missing_genes_template: "results/list_missing_genes_coverage_gram_{group}.txt"
  updated_coverage_template: "results/updated_gene_coverage_gram_{group}.tsv"

# Scripts
scripts:
  classify_gram: "scripts/bacdive_classification.py"
  supplement_gram_classification: "scripts/supplement_bacdive_gram_classification.py"
  fetch_quickgo: "scripts/fetch_quickgo_data.py"
  gene_filtering: "scripts/filter_quickgo_data.py"
  gene_coverage: "scripts/gene_taxa_coverage.py"
  gene_coverage_append: "scripts/append_gene_coverage.py"
  filter_coverage: "scripts/filter_coverage_count.py"
  select_proteins: "scripts/select_proteins.py"
  download_proteins: "scripts/download_proteins.py"
  get_msa_sequences: "scripts/get_msa_sequences.py"
  conserved_aminoacids: "scripts/conserved_aminoacids.py"

# MAFFT settings
mafft:
  threads: 8

# Gram thresholds for gene filtering (now using 50% coverage for all)
gram_thresholds:
  positive: 50
  negative: 50

# Protein selection numbers
protein_selection:
  positive: 3
  negative: 5

# Defined groups
groups:
  - positive
  - negative

species_batches:
  - analysis_1
  #- analysis_2
  #- analysis_3

species_files:
  analysis_1: "config/species/analysis_1.txt"
  #analysis_2: "config/species/analysis_2.txt"
  #analysis_3: "config/species/analysis_3.txt"

quickgo_paramsets:
  - params_1
  #- params_2
  #- params_3


cache:
  checked_gene_species: cache/checked_gene_species.tsv
